### ISSUE TITLE
configcat-react deps is installing an incompatible configcat-common dependency

### ISSUE THREAD

**Issue by dcefram** [configcat/react-sdk#49]
### Describe the bug

When doing a fresh installation of `configcat-react`, it would install a peer deps of `configcat-common`. The problem is that the peer deps is not compatible.

`configcat-react` version `4.2.0` requires `configcat-common` version `^9.1.0`. 

This installs version `9.2.0` which is apparently not compatible with `configcat-react` version `4.2.0`.

### To reproduce

1. Do a fresh install `npm i configcat-react`
2. Try to import `configcat-react` in your react project
3. It would throw errors related to configcat-react trying to import something that is not exported anymore.

### Expected behavior

No errors should show when importing configcat-react

### Screenshots

![share-rmrz-ph 2024-01-16 at 23 49 56@2x](https://github.com/configcat/react-sdk/assets/43171726/c55ad691-dcad-4f7b-95b5-71b37578b524)

### SDK version

`configcat-react` version 4.2.0

### SDK configuration

Please copy paste the client initialization code snippet, so we can see how you are using the SDK.

### Logs

N/A

### Language/Framework version

N/A

### Platform

MacOS

Note that the workaround is to explicitly install `configcat-common` version `~9.1.0` in my own package.json.

**Comment by adams85** [comment]
Hi @dcefram, 

it looks like we've been bitten by the ^ version references of NPM.

Because of the ^ reference, configcat-common v9.2.0 is resolved instead of v9.1.0 and the former is incompatible with configcat-react v4.2.0 indeed as configcat-common v9.2.0 comes with a minor public API breaking change (where public means public to the react-sdk but not public to the consumers of the react-sdk). Yet this breaks configcat-react v4.2.0 and earlier.

After discussing the issue, we plan to solve the issue with fixed version references.

Sorry for the inconvience, the new version will be available soon.

**Comment by adams85** [comment]
FYI, configcat-react v4.3.0 has been released and should fix the issue. Please let us know if you still experience problems.
